### PR TITLE
fix: 🐛 add config option to change closed issue message

### PR DESCRIPTION
**Pull request by damusix**
Allow the ability to modify closed issues message for use cases where
you don't want to close the issues.

✅ Closes: #215

### CODE REVIEW

**Comment by rodrigograca31** [comment]
I'm a bit tired today to make a proper review and approved it but from what I saw it looks good and ready.

I will look at it properly tomorrow or something.

ping me if I forget :sweat_smile:

**Comment by damusix** [comment]
@rodrigograca31 remindeerrrrr ring ringgg

**Comment by rodrigograca31** [comment]
@damusix looks perfect.

I wanted to ask you to add it to the `README.md` but seems that similar configs are also not there... :man_shrugging:

**Comment by rodrigograca31** [comment]
Thank you for your contribution :heart:

**Pull request merged**
