### PR TITLE
chore: 🤖 upgrade eslint

### PR DESCRIPTION
**Pull request by rodrigograca31**
import mailonline eslint config to this project

✅ Closes: #205 #171

Tests should be passing and we can finally upgrade eslint. :smiley:

### CODE REVIEW

**Comment by streamich** [comment]
Build version: __`4.5.0-pr-208.967`__ :crossed_fingers: [`eslint-upgrade`](https://github.com/streamich/git-cz/tree/eslint-upgrade) on [*Travis*](https://travis-ci.org/streamich/git-cz/builds/187000646) :tada:

**Comment by rodrigograca31** [comment]
Just noticed I got merge permissions... 🤔

But it's not ethical to merge my own code... 😂

Someone else should review it first... @StanLindsey perhaps?

**Comment by rodrigograca31** [comment]
@streamich sorry to ping you for this, but there are multiple PRs that are ready to be merged (4) and solve various issues.

Should I go ahead and merge them? or that's not the best idea? 
Will it create a new release?

Thanks for your time. :heart:

**Pull request merged**
