### PR TITLE
chore: 🤖 update semantic-release related packages

### PR DESCRIPTION
**Pull request by rodrigograca31**
✅ Closes: #202 #226

Hi @streamich
**I need you to manually review and accept this PR.**

The breaking change of the updated packages [seems to be](https://github.com/streamich/git-cz/pull/202) `Require Node.js >= 10.18` but since this involves the release bot/code and I don't want to break future releases I need you to approve it and make sure nothing in the release process breaks.

Thanks

### CODE REVIEW

**Comment by streamich** [comment]
Build version: __`4.5.0-pr-233.1149`__ :crossed_fingers: [`semantic-release`](https://github.com/streamich/git-cz/tree/semantic-release) on [*Travis*](https://travis-ci.org/streamich/git-cz/builds/208344508) :tada:

**Comment by streamich** [comment]
Build version: __`4.5.0-pr-233.1149`__ :crossed_fingers: [`semantic-release`](https://github.com/streamich/git-cz/tree/semantic-release) on [*Travis*](https://travis-ci.org/streamich/git-cz/builds/208344508) :tada:

**Comment by streamich** [comment]
Build version: __`4.5.0-pr-233.1149`__ :crossed_fingers: [`semantic-release`](https://github.com/streamich/git-cz/tree/semantic-release) on [*Travis*](https://travis-ci.org/streamich/git-cz/builds/208344508) :tada:

**Comment by rodrigograca31** [comment]
Since @streamich wasnt able to review this in about 1 year Im taking the lead and merging it.

also praying nothing in the releases automation breaks...

**Pull request merged**
