### PR TITLE
feat: 🎸 recursively search parent folders for config file

### PR DESCRIPTION
**Pull request by StanLindsey**
✅ Closes: #60 - Global Config

### CODE REVIEW

**Comment by StanLindsey** [comment]
@streamich ?

**Comment by rodrigograca31** [comment]
Closes: #165

**Comment by rodrigograca31** [comment]
The code looks perfect. I tried to install it and run it on my machine but its almost impossible.... 😂

I dont have enough knowledge of npm stuff and it was a mess...

**Comment by rodrigograca31** [comment]
@streamich can you please accept this PR? it will greatly increase productivity. 
(careful with last commit)

Thanks for your time.

**Comment by StanLindsey** [comment]
Oh yeah, this probs isn't ready for an MR now. 

I got bored of waiting and released this change under https://www.npmjs.com/package/@stanlindsey/git-cz

@rodrigograca31 - you can use that one now if you want the feature.

**Comment by rodrigograca31** [comment]
Yeah it works!
For those interested: 

```bash
npm uninstall -g git-cz
npm install -g @stanlindsey/git-cz
```

Then create the `changelog.config.js` file (in `/home/USER/git/`?) or wherever you prefer and profit :joy: 

thanks @StanLindsey 

here I just duplicated the emoji:

image


P.S. I hope this project was not abandoned but I see a few important PRs not merged... :sob:

**Comment by StanLindsey** [comment]
Thanks @rodrigograca31 - I'm likely going to go through the PRs in this repo and review and port them over. 

I don't have a tonne of free time, so I'd much prefer that @streamich doesn't abandon this, but i am happy assisting in maintaining `streamich/git-cz`

**Comment by rodrigograca31** [comment]
Me too. I'm happy to help reviewing code and merging PRs. 

Like I said already looked at a few of them and they are good.
I also maintain a few other npm packages already: https://www.npmjs.com/~rodrigograca31

**Comment by StanLindsey** [comment]
@rodrigograca31 - I just pushed another verison which includes some niceties.

**Comment by rodrigograca31** [comment]
Nice changes!

**Comment by Flo-Slv** [comment]
@streamich  Hi !

Do you will add this changes ? It wil be great !

**Pull request closed without merging**
