### PR TITLE
fix: 🐛 check for staged files

### PR DESCRIPTION
**Pull request by rodrigograca31**
removes use of ! and shows warning instead of error

Original issue: #177

### CODE REVIEW

**Comment by rodrigograca31** [comment]
The failing test is because of the dot `.` that was introduced.

https://travis-ci.com/github/streamich/git-cz/builds/168357772#L257-L258

I can fix that right after in another branch/PR

**Comment by StanLindsey** [comment]
@rodrigograca31 - can you fix it in this branch for this PR instead of opening a new one?

**Comment by rodrigograca31** [comment]
Sure, will try. I think the the test was fixed but I couldnt re run he build...

**Comment by streamich** [comment]
Build version: __`4.5.0-pr-181.833`__ :crossed_fingers: [`staged-files-check`](https://github.com/streamich/git-cz/tree/staged-files-check) on [*Travis*](https://travis-ci.org/streamich/git-cz/builds/168606656) :tada:

**Pull request merged**
